name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build (default)
      run: cargo build --verbose
    - name: Build (embed)
      run: cargo build --verbose --features embed
    - name: Test (default)
      run: cargo test --verbose
    - name: Test (embed)
      run: cargo test --verbose --features embed
    - name: Clippy (default)
      run: cargo clippy -- -D warnings
    - name: Clippy (embed)
      run: cargo clippy --features embed -- -D warnings
