name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake
    - name: Build (native, CPU)
      run: cargo build --verbose --no-default-features --features native
    - name: Test (native, CPU)
      run: cargo test --verbose --no-default-features --features native
    - name: Clippy (native, CPU)
      run: cargo clippy --no-default-features --features native -- -D warnings
